const upgradesData = [
  {
    id: "1",
    type: "upgrades",
    title: "Fishercat",
    description: "Each upgrade gives you + 0.05x CPS",
    initPrice: 20,
    price: null,
    level: 0,
    bonusType: "cps",
    bonusPerLvl: 0.05,
  },
  {
    id: "2",
    type: "upgrades",
    title: "Builders",
    description: "Each upgrade gives you + 0.1x CPS ",
    initPrice: 100,
    price: null,
    level: 0,
    bonusType: "cps",
    bonusPerLvl: 0.1,
  },
  {
    id: "3",
    type: "upgrades",
    title: "Cat house",
    description: "Each upgrade gives you + 0.25x CPS ",
    initPrice: 500,
    price: null,
    level: 0,
    bonusType: "cps",
    bonusPerLvl: 0.25,
  },
  {
    id: "4",
    type: "upgrades",
    title: "Farmer",
    description: "Each upgrade gives you + 0.5x CPS ",
    initPrice: 2500,
    price: null,
    level: 0,
    bonusType: "cps",
    bonusPerLvl: 0.5,
  },
  {
    id: "5",
    type: "upgrades",
    title: "Driver",
    description: "Each upgrade gives you + 1x CPS ",
    initPrice: 10000,
    price: null,
    level: 0,
    bonusType: "cps",
    bonusPerLvl: 1,
  },
  {
    id: "6",
    type: "upgrades",
    title: "Warrior",
    description: "Each upgrade gives you + 2.5x CPS ",
    initPrice: 50000,
    price: null,
    level: 0,
    bonusType: "cps",
    bonusPerLvl: 2.5,
  },
];

const itemsData = [
  {
    id: "1",
    type: "mainCat",
    title: "Black skin",
    description: "Upgrade into black cat",
    price: 1,
    bonusType: "cm",
    bonusAmount: 2,
    purchased: false,
  },
  {
    id: "2",
    type: "mainCat",
    title: "Ginger skin",
    description: "Upgrade into ginger cat",
    price: 1,
    bonusType: "cm",
    bonusAmount: 5,
    purchased: false,
  },
  {
    id: "3",
    type: "mainCat",
    title: "Brown skin",
    description: "Upgrade into brown cat",
    price: 1,
    bonusType: "cm",
    bonusAmount: 10,
    purchased: false,
  },
];

export { upgradesData, itemsData };
